### ISSUE TITLE
Setup CI/CD and static analysis

### ISSUE THREAD

**Issue by dspezia-1a** [AmadeusITGroup/cpubench1A#3]
We have to setup Travis and some static analysis tool.

**Comment by Nexucis** [comment]
maybe if your needs are quite simple, a quickway could be to use the github actions. Specially if you just need to run 
[golangci/golangci-lint](https://github.com/golangci/golangci-lint).

You can even combine both if you want.

**Comment by Nexucis** [comment]
and maybe it would be interesting to integrate the build of the artifact in the CI. So like that when tagging the repo, you will be able to deliver the binary and supporting multiple different architecture automatically.

**Comment by dspezia-1a** [comment]
Thanks. Yes, I was considering only the basics. The issue was a reminder for FiX.

**Comment by harshavmb** [comment]
> and maybe it would be interesting to integrate the build of the artifact in the CI. So like that when tagging the repo, you will be able to deliver the binary and supporting multiple different architecture automatically.

@dspezia-1a , I propose to use [goreleaser](https://goreleaser.com/) for CI/CD for go binaries. We use the same binary for building Terraform plugins internally. It has lot of cool features like pre-hooks, multi OS, CPU arch support, archive & binary signature etc., & Opensource..
